SELECT t1.PRODUCT_CODE, IFNULL(t1.PRICE * SUM(t2.SALES_AMOUNT),0) AS SALES
  FROM PRODUCT t1
       LEFT OUTER JOIN OFFLINE_SALE t2 ON t1.PRODUCT_ID = t2.PRODUCT_ID
GROUP BY t1.PRODUCT_ID
ORDER BY SALES DESC, t1.PRODUCT_CODE