WITH FOOD_TYPE_WITH_MAX_FAVORITES AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
      FROM REST_INFO
    GROUP BY FOOD_TYPE
    ORDER BY FOOD_TYPE DESC
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
  FROM REST_INFO
 WHERE (FOOD_TYPE, FAVORITES) IN ( SELECT FOOD_TYPE, MAX_FAVORITES
                                    FROM FOOD_TYPE_WITH_MAX_FAVORITES )
ORDER BY FOOD_TYPE DESC