WITH ECOLI_RANKING AS (
SELECT ID,
       ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) / COUNT(*) OVER () * 100 PER
  FROM ECOLI_DATA
)

SELECT ID,
       CASE WHEN PER <= 25 THEN 'CRITICAL'
            WHEN PER <= 50 THEN 'HIGH'
            WHEN PER <= 75 THEN 'MEDIUM'
            ELSE 'LOW' END COLONY_NAME
  FROM ECOLI_RANKING
ORDER BY ID