SELECT t1.ANIMAL_ID, t1.ANIMAL_TYPE, t1.NAME
  FROM ANIMAL_INS t1
       LEFT JOIN ANIMAL_OUTS t2 ON t1.ANIMAL_ID = t2.ANIMAL_ID
 WHERE t1.SEX_UPON_INTAKE LIKE 'Intact%'
   AND (t2.SEX_UPON_OUTCOME LIKE 'Spayed%' OR t2.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY t1.ANIMAL_ID