SELECT t1.REST_ID
     , MAX(t1.REST_NAME) AS REST_NAME
     , MAX(t1.FOOD_TYPE) AS FOOD_TYPE
     , MAX(t1.FAVORITES) AS FAVORITE
     , MAX(t1.ADDRESS) AS ADDRESS
     , ROUND(AVG(t2.REVIEW_SCORE),2) AS REVIEW_SCORE_AVG
  FROM REST_INFO AS t1, REST_REVIEW AS t2
 WHERE t1.REST_ID = t2.REST_ID
   AND t1.ADDRESS LIKE '서울%'
GROUP BY t1.REST_ID
ORDER BY REVIEW_SCORE_AVG DESC, FAVORITE DESC