SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, t2.GENDER, COUNT(DISTINCT t1.USER_ID) USERS
  FROM ONLINE_SALE t1
       JOIN USER_INFO t2 ON t1.USER_ID = t2.USER_ID
 WHERE t2.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), t2.GENDER
ORDER BY YEAR, MONTH, GENDER