SELECT COUNT(*) AS FISH_COUNT, MAX(t2.FISH_NAME) AS FISH_NAME
  FROM FISH_INFO t1
       LEFT OUTER JOIN FISH_NAME_INFO t2 ON t1.FISH_TYPE = t2.FISH_TYPE
GROUP BY t1.FISH_TYPE
ORDER BY FISH_COUNT DESC