SELECT t1.PRODUCT_ID, t1.PRODUCT_NAME, t1.PRICE * SUM(t2.AMOUNT) AS TOTAL_SALES
  FROM FOOD_PRODUCT t1
       LEFT JOIN FOOD_ORDER t2 ON t1.PRODUCT_ID = t2.PRODUCT_ID
 WHERE DATE_FORMAT(t2.PRODUCE_DATE,'%Y%m') = '202205'
GROUP BY t1.PRODUCT_ID, t1.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, t1.PRODUCT_ID