WITH CTE AS (
SELECT t1.HISTORY_ID,
       t2.CAR_TYPE,
       t2.DAILY_FEE,
       DATEDIFF(END_DATE, START_DATE) + 1 RENTAL_DAY,
       CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN 0
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN 7
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN 30
            ELSE 90 END AS DURATION_TYPE_CODE
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY t1
       JOIN CAR_RENTAL_COMPANY_CAR t2 ON t1.CAR_ID = t2.CAR_ID
 WHERE t2.CAR_TYPE = '트럭'
)

SELECT t1.HISTORY_ID,
       ROUND((t1.DAILY_FEE * RENTAL_DAY * IFNULL((100 - DISCOUNT_RATE) / 100, 1)),0) FEE
  FROM CTE t1
       LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN t2 ON t1.CAR_TYPE = t2.CAR_TYPE
                                                AND t1.DURATION_TYPE_CODE = CAST(t2.DURATION_TYPE AS UNSIGNED)
ORDER BY FEE DESC, HISTORY_ID DESC