SELECT t1.APNT_NO, t2.PT_NAME, t1.PT_NO, t1.MCDP_CD, t3.DR_NAME, t1.APNT_YMD
  FROM APPOINTMENT t1
       JOIN PATIENT t2 ON t1.PT_NO = t2.PT_NO
       JOIN DOCTOR t3 ON t1.MDDR_ID = t3.DR_ID
 WHERE t1.MCDP_CD = 'CS'
   AND DATE_FORMAT(APNT_YMD, '%Y%m%d') = '20220413'
   AND APNT_CNCL_YN = 'N'
 ORDER BY APNT_YMD