WITH RECURSIVE HOURS AS (
SELECT 0 AS H
UNION ALL
SELECT H + 1 FROM HOURS WHERE H < 23
)

SELECT t1.H AS HOUR, COUNT(t2.ANIMAL_ID) AS COUNT
  FROM HOURS t1
       LEFT OUTER JOIN ANIMAL_OUTS t2 ON t1.H = HOUR(t2.DATETIME)
GROUP BY t1.H
ORDER BY t1.H