SELECT t1.WRITER_ID, t2.NICKNAME, SUM(t1.PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD AS t1,
       USED_GOODS_USER AS t2
 WHERE t1.WRITER_ID = t2.USER_ID
   AND t1.STATUS = 'DONE'
GROUP BY t1.WRITER_ID
HAVING SUM(t1.PRICE) >= 700000
ORDER BY TOTAL_SALES