SELECT t1.EMP_NO, t1.EMP_NAME,
       CASE WHEN SUM(t2.SCORE) >= 192 THEN 'S'
            WHEN SUM(t2.SCORE) >= 180 THEN 'A'
            WHEN SUM(t2.SCORE) >= 160 THEN 'B'
            ELSE 'C' END GRADE,
       CASE WHEN SUM(t2.SCORE) >= 192 THEN CAST(t1.SAL * 20 / 100 AS UNSIGNED)
            WHEN SUM(t2.SCORE) >= 180 THEN CAST(t1.SAL * 15 / 100 AS UNSIGNED)
            WHEN SUM(t2.SCORE) >= 160 THEN CAST(t1.SAL * 10 / 100 AS UNSIGNED)
            ELSE 0 END BONUS
  FROM HR_EMPLOYEES t1
       JOIN HR_GRADE t2 ON t1.EMP_NO = t2.EMP_NO
GROUP BY t1.EMP_NO
ORDER BY t1.EMP_NO