SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
  FROM MEMBER_PROFILE t1
       JOIN REST_REVIEW t2 ON t1.MEMBER_ID = t2.MEMBER_ID
WHERE t1.MEMBER_ID = 
(
    SELECT MEMBER_ID
      FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT