SELECT t3.ITEM_ID, t3.ITEM_NAME, t3.RARITY 
  FROM ( SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE' ) AS t1,
       ITEM_TREE AS t2,
       ITEM_INFO AS t3
 WHERE t1.ITEM_ID = t2.PARENT_ITEM_ID AND t2.ITEM_ID = t3.ITEM_ID
ORDER BY ITEM_ID DESC