SELECT CAST(DATE_FORMAT(START_DATE, '%m') AS UNSIGNED) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE DATE_FORMAT(START_DATE, '%Y%m') IN ('202208', '202209', '202210')
   AND CAR_ID IN (
    SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE DATE_FORMAT(START_DATE, '%Y%m') IN ('202208', '202209', '202210')
    GROUP BY CAR_ID HAVING COUNT(*) >= 5
)
GROUP BY DATE_FORMAT(START_DATE, '%m'), CAR_ID
ORDER BY MONTH, CAR_ID DESC