SELECT DISTINCT t1.CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR t1
       JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY t2 ON t1.CAR_ID = t2.CAR_ID
 WHERE t1.CAR_TYPE = '세단' AND MONTH(t2.START_DATE) = 10
ORDER BY CAR_ID DESC