WITH MAX_LENGTH_FISH_TYPE AS (
    SELECT FISH_TYPE, MAX(LENGTH) MAX_LENGTH FROM FISH_INFO GROUP BY FISH_TYPE
)

SELECT t1.ID, t2.FISH_NAME, t1.LENGTH
  FROM FISH_INFO t1
       JOIN FISH_NAME_INFO t2 ON t1.FISH_TYPE = t2.FISH_TYPE
 WHERE (t1.FISH_TYPE, t1.LENGTH) IN ( SELECT FISH_TYPE, MAX_LENGTH FROM MAX_LENGTH_FISH_TYPE )
ORDER BY t1.ID