WITH HR_EMPLOYEES_SCORE_2022 AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
      FROM HR_GRADE
     WHERE YEAR = 2022
    GROUP BY EMP_NO
)

SELECT t1.SCORE, t1.EMP_NO, t2.EMP_NAME, t2.POSITION, t2.EMAIL
  FROM HR_EMPLOYEES_SCORE_2022 t1
       LEFT OUTER JOIN HR_EMPLOYEES t2 ON t1.EMP_NO = t2.EMP_NO
ORDER BY t1.SCORE DESC
LIMIT 1