SELECT LEFT(FORMAT(t1.CREATED_DATE, '%Y%m'),7), t1.TITLE, t1.BOARD_ID,
       t2.REPLY_ID, t2.WRITER_ID, t2.CONTENTS, t2.CREATED_DATE
  FROM USED_GOODS_BOARD AS t1
     , USED_GOODS_REPLY AS t2
 WHERE t2.BOARD_ID = t1.BOARD_ID
   #AND FORMAT(t1.CREATED_DATE, '%Y%m') = '202210'
ORDER BY t2.CREATED_DATE, t1.TITLE