SELECT t1.DEPT_ID, t1.DEPT_NAME_EN, ROUND(AVG(t2.SAL),0) AVG_SAL
  FROM HR_DEPARTMENT t1
       JOIN HR_EMPLOYEES t2 ON t1.DEPT_ID = t2.DEPT_ID
GROUP BY t1.DEPT_ID, t1.DEPT_NAME_EN
ORDER BY AVG_SAL DESC