SELECT CONCAT('/home/grep/src/', t2.BOARD_ID, '/', t2.FILE_ID, t2.FILE_NAME, t2.FILE_EXT) AS FILE_PATH
  FROM ( SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1 ) AS t1
       LEFT OUTER JOIN USED_GOODS_FILE AS t2 ON t1.BOARD_ID = t2.BOARD_ID
ORDER BY t2.FILE_ID DESC