SELECT t1.BOOK_ID, t2.AUTHOR_NAME, DATE_FORMAT(t1.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
  FROM BOOK t1
       LEFT JOIN AUTHOR t2 ON t1.AUTHOR_ID = t2.AUTHOR_ID
 WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE